language: ruby

sudo: false

cache: bundler

notifications:
  email:
    on_success: never

branches:
  only: master

rvm: 2.1

env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: 
- bundle exec jekyll build

after_success:
- bundle exec htmlproofer ./_site --disable-external
