language: ruby

sudo: false

cache: bundler

notifications:
  email:
    on_success: never

branches:
  only: master

env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  include:
  - rvm: 2.1
    gemfile: gemfiles/2.1.Gemfile
  - rvm: 2.3
    gemfile: gemfiles/2.3.Gemfile

install:
- bundle install

script: 
- ls -lA
- bundle exec jekyll build --trace

after_success:
- bundle exec htmlproofer ./_site --disable-external
