language: ruby

sudo: false

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

notifications:
  email:
    on_success: never

branches:
  only: master

env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  include:
  - rvm: 2.1
    gemfile: gemfiles/2.1.Gemfile
  - rvm: 2.3
    gemfile: gemfiles/2.3.Gemfile

install:
- bundle install

script: 
- bundle exec jekyll build --trace

# https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis
after_success:
- bundle exec htmlproofer --check-opengraph --check-sri --check-html --check-img-http --enforce-https --timeframe 4w ./_site
