theme: minima
title: Daniels user page
description: >
  About me (dleidert) and my open source work
author: Daniel Leidert
email: daniel.leidert@wgdd.de
lang: en
show_downloads: true
show_excerpts: true
google_analytics:
google_site_verification: gPitPikijaA6VSAckqTh85FsSKzUU0kuVRIRpLqNA08

exclude:
  - Gemfile
  - Gemfile.lock
  - /node_modules
  - /vendor/
  - .travis.yml
  - ".git*"
  - "**/README.md"

header_pages:
   - debian.md
   - windows.md
   - github.md

#social:
#  name: Daniel Leidert
#  links:
#    - https://github.com/dleidert/
#    - https://instagram.com/daniel.leidert/
#    - https://salsa.debian.org/dleidert
#    - https://www.xing.com/profile/Daniel_Leidert
#    - https://m.youtube.com/channel/UCcByb2fCTx7B8QwZBdGxDgA

# minima >2.5.0 (current master)
minima:
  social_links:
    github: dleidert
    instagram: daniel.leidert
    youtube_channel: UCcByb2fCTx7B8QwZBdGxDgA
    xing: Daniel_Leidert
    debian: dleidert
    gnupg: 0xF11F9DE2C296D05D
    rss: rss

# minima 2.5.0
github_username: dleidert
instagram_username: daniel.leidert
xing_username: Daniel_Leidert
debian_username: dleidert
gnupg_key: 0xF11F9DE2C296D05D
rss: rss

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
